// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/supplier/uc.supplier.dep.go

// Package mock_supplier is a generated GoMock package.
package supplier

import (
	context "context"
	reflect "reflect"

	model "github.com/androsyz/inventory/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockrepoSupplierInterface is a mock of repoSupplierInterface interface.
type MockrepoSupplierInterface struct {
	ctrl     *gomock.Controller
	recorder *MockrepoSupplierInterfaceMockRecorder
}

// MockrepoSupplierInterfaceMockRecorder is the mock recorder for MockrepoSupplierInterface.
type MockrepoSupplierInterfaceMockRecorder struct {
	mock *MockrepoSupplierInterface
}

// NewMockrepoSupplierInterface creates a new mock instance.
func NewMockrepoSupplierInterface(ctrl *gomock.Controller) *MockrepoSupplierInterface {
	mock := &MockrepoSupplierInterface{ctrl: ctrl}
	mock.recorder = &MockrepoSupplierInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrepoSupplierInterface) EXPECT() *MockrepoSupplierInterfaceMockRecorder {
	return m.recorder
}

// CreateSupplier mocks base method.
func (m *MockrepoSupplierInterface) CreateSupplier(ctx context.Context, supplier *model.Supplier) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupplier", ctx, supplier)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSupplier indicates an expected call of CreateSupplier.
func (mr *MockrepoSupplierInterfaceMockRecorder) CreateSupplier(ctx, supplier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupplier", reflect.TypeOf((*MockrepoSupplierInterface)(nil).CreateSupplier), ctx, supplier)
}

// GetSuppliers mocks base method.
func (m *MockrepoSupplierInterface) GetSuppliers(ctx context.Context) ([]*model.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuppliers", ctx)
	ret0, _ := ret[0].([]*model.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuppliers indicates an expected call of GetSuppliers.
func (mr *MockrepoSupplierInterfaceMockRecorder) GetSuppliers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuppliers", reflect.TypeOf((*MockrepoSupplierInterface)(nil).GetSuppliers), ctx)
}
